##This script will create a tidy data set from the activity data generated by the Samsung Galaxy S smartphone

##Load dplr library
  library(dplyr)

##Set the working directory
  setwd("C:/Users/m182531/Documents/UCI HAR Dataset")
  
##File existence check
  if(!file.exists("features.txt")) {
    stop(paste("File does not exist:", "features.txt"))
  }
  if(!file.exists("subject_test.txt")) {
    stop(paste("File does not exist:", "subject_test.txt"))
  }
  if(!file.exists("X_test.txt")) {
    stop(paste("File does not exist:", "X_test.txt"))
  }
  if(!file.exists("y_test.txt")) {
    stop(paste("File does not exist:", "y_test.txt"))
  }
  if(!file.exists("subject_train.txt")) {
    stop(paste("File does not exist:", "subject_train.txt"))
  }
  if(!file.exists("X_train.txt")) {
    stop(paste("File does not exist:", "X_train.txt"))
  }
  if(!file.exists("y_train.txt")) {
    stop(paste("File does not exist:", "y_train.txt"))
  }
  
##Read/load "features.txt" file as a data frame, remove white space, transpose rows to columns
  features <- read.table("features.txt", sep="", header=FALSE, strip.white=TRUE, stringsAsFactors=FALSE)
  features <- as.data.frame(t(features[2]))
  
##Check dim of features (should be 1x561)
  dim(features)
  
##Clean up variable names (change to lowercase, remove parentheses, change "-" and "," to ".", remove any excess ".")
  features <- features %>% tolower() %>% gsub("\\(","", .) %>% gsub("\\)", "", .) %>% gsub("-", "\\.", .) %>% gsub(",", "\\.", .) %>% gsub("\\.{2,}", ".", .)
  
##Read/load files as data frames, define column names, remove white space
  subject_test <- read.table("subject_test.txt", sep="", col.names="subjectid", strip.white=TRUE, stringsAsFactors=FALSE) ##Contains study ids for the test group
  X_test <- read.table("X_test.txt", sep="", col.names=features, strip.white=TRUE, stringsAsFactors=FALSE) ##Contains the activity data for the test group
  y_test <- read.table("y_test.txt", sep="", col.names="activitylabel", strip.white=TRUE, stringsAsFactors=FALSE) ##Contains the activity labels for the test group
  subject_train <- read.table("subject_train.txt", sep="", col.names="subjectid", strip.white=TRUE, stringsAsFactors=FALSE) ##Contains study ids for the train group
  X_train <- read.table("X_train.txt", sep="", col.names=features, strip.white=TRUE, stringsAsFactors=FALSE) ##Contains the activity data for the train group
  y_train <- read.table("y_train.txt", sep="", col.names="activitylabel", strip.white=TRUE, stringsAsFactors=FALSE) ##Contains the activity labels for the train group
  
##Check the dimensions of each data frame.
##All of the test files should contain the same number of rows. subject_test and y_test should have 1 column. X_test should have 561 columns.
  dim(subject_test)
  dim(y_test)
  dim(X_test)
##All of the train files should contain the same number of rows. subject_train and y_train should have 1 column. X_train should have 561 columns.
  dim(subject_train)
  dim(y_train)
  dim(X_train)
  
##Create a list of activity labels. Convert the activity labels contained in y_test and y_train from numbers (1, 2, 3, 4, 5, 6) to characters(1=walking, 2=walkingupstairs, 3=walkingdownstairs, 4=sitting, 5=standing, 6=laying).
  activity_labels <- c("walking", "walkingupstairs", "walkingdownstairs", "sitting", "standing", "laying")
  y_test$activitylabel <- activity_labels[y_test$activitylabel]
  y_train$activitylabel <- activity_labels[y_train$activitylabel]
  
##Combine test files, combine train files
  test_data <- cbind(subject_test, y_test, X_test)
  train_data <- cbind(subject_train, y_train, X_train)
  
#Check dim of test_data and train_data. (should be 2947x563 and 7352x563 respectively)
  dim(test_data)
  dim(train_data)
  
##Combine test_data with train_data, sort data by subjectid, then activitylabel
  merged_data <- rbind(test_data, train_data)
  merged_data[order(merged_data$subjectid, merged_data$activitylabel), ]
  
##Check dim of merged_data (should be 10,299 X 563)
  dim(merged_data)
  
##Keep only measurements on the mean or standard deviation for each measurement. Retain the first two columns (subjectid and activitylabel)
  merged_data <- merged_data %>% select(1:2, matches("[Mm][Ee][Aa][Nn]") | matches("[Ss][Tt][Dd]"))
  
##Save merged_data to csv
  write.csv(merged_data, file="merged_data.csv", row.names=FALSE)
  
##Create a second independent data set with the average of each variable for each activity and each subject
  summary_data <- merged_data %>% group_by(subjectid, activitylabel) %>% summarize(across(everything(), \(x) mean(x, na.rm=TRUE), .names="avg.{col}"))
  
##Save summary_data to csv
  write.csv(summary_data, file="summary_data.csv", row.names=FALSE)
  